# -*- coding: utf-8 -*-
"""Lab Oracle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWTydNpQIj1avi63ajJ4dcRUVCoAoqpy
"""

import cv2
import numpy as np

def lab_oracle_solver(img_in, img_out):
    """
    Analyzes visual differences and maps them to Labs .
    """
    steps = []

    # Pre-process
    is_color_in = len(img_in.shape) == 3
    is_color_out = len(img_out.shape) == 3
    gray_in = cv2.cvtColor(img_in, cv2.COLOR_BGR2GRAY) if is_color_in else img_in
    gray_out = cv2.cvtColor(img_out, cv2.COLOR_BGR2GRAY) if is_color_out else img_out

    # Image Negative
    # Check if intensities are inverted: s = 255 - r
    inverted_check = cv2.absdiff(255 - gray_in, gray_out)
    if np.mean(inverted_check) < 20:
        steps.append({
            "lab": "Lab 3 (Point Processing)",
            "method": "Image Negative",
            "formula": "s = 255 - r",
            "reason": "Pixels are inverted; dark areas became bright and vice versa."
        })

    # Lab 2: Thresholding
    unique_vals = np.unique(img_out)
    if len(unique_vals) == 2:
        steps.append({
            "lab": "Lab 2 (Thresholding)",
            "method": "Global Thresholding",
            "formula": "T(x,y) = 255 if I > T else 0",
            "reason": "The image has been converted to a binary (Black/White) format."
        })

    # Morphological Processing
    # Only check if the output is binary (from previous step)
    if len(unique_vals) == 2:
        # Check for Erosion/Dilation by comparing areas
        area_in = np.sum(gray_in > 0)
        area_out = np.sum(gray_out > 0)
        if area_out < area_in * 0.8:
            steps.append({"lab": "Lab 4", "method": "Erosion", "reason": "Object boundaries have shrunk."})
        elif area_out > area_in * 1.2:
            steps.append({"lab": "Lab 4", "method": "Dilation", "reason": "Objects have expanded/thickened."})

    #  Edge Detection
    # Check for Edge Maps (Sobel/Canny)
    lap_var_in = cv2.Laplacian(gray_in, cv2.CV_64F).var()
    lap_var_out = cv2.Laplacian(gray_out, cv2.CV_64F).var()
    if np.mean(gray_out) < 50 and lap_var_out > lap_var_in:
        steps.append({
            "lab": "Lab 2 / Lab 5",
            "method": "Sobel / Canny Edge Detection",
            "formula": "|G| = sqrt(Gx^2 + Gy^2)",
            "reason": "Output is a sparse map of intensity gradients (edges)."
        })

    # Frequency Domain (Blurring)
    # Low Pass Filters (Ideal, Butterworth, Gaussian)
    if lap_var_out < lap_var_in * 0.4 and np.mean(gray_out) > 50:
        steps.append({
            "lab": "Lab 6",
            "method": "Low Pass Filtering (ILPF/BLPF/GLPF)",
            "reason": "High frequency details (noise/edges) were removed, resulting in a blur."
        })

    # Lab 3: Power-Law (Gamma)
    # Check if intensity distribution shifted non-linearly
    mean_in, mean_out = np.mean(gray_in), np.mean(gray_out)
    if abs(mean_in - mean_out) > 30 and len(unique_vals) > 50:
        if mean_out > mean_in:
            steps.append({"lab": "Lab 3", "method": "Log or Gamma Correction (gamma < 1)", "formula": "s = c*r^gamma", "reason": "Dark areas were expanded/brightened."})
        else:
            steps.append({"lab": "Lab 3", "method": "Gamma Correction (gamma > 1)", "formula": "s = c*r^gamma", "reason": "The image intensity was compressed/darkened."})

    # Enhancement Pipeline (Sharpening)
    # Check if output is a sharpened version: f + Mask
    if lap_var_out > lap_var_in * 1.2 and np.mean(gray_out) > 50:
        steps.append({
            "lab": "Lab 5",
            "method": "Sharpening Pipeline",
            "formula": "g = f + Mask_norm",
            "reason": "Edges were emphasized while maintaining the original image background."
        })

    return steps