# -*- coding: utf-8 -*-
"""color.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EeYC7GK_3vfbgTH_ZO8ee9xUpZ5jKCru
"""

"""Color space + channel operations"""

from __future__ import annotations

import cv2
import numpy as np

from app.cv_ops._params import clamp_float, clamp_int

# COLOR SPACE OPERATIONS

def apply_to_grayscale(bgr: np.ndarray, _params: dict) -> np.ndarray:
    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    return cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)


def apply_bgr_to_hsv_and_back(bgr: np.ndarray, _params: dict) -> np.ndarray:
    hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
    return cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)


def apply_bgr_to_lab_and_back(bgr: np.ndarray, _params: dict) -> np.ndarray:
    lab = cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB)
    return cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)


def apply_bgr_to_ycrcb_and_back(bgr: np.ndarray, _params: dict) -> np.ndarray:
    ycrcb = cv2.cvtColor(bgr, cv2.COLOR_BGR2YCrCb)
    return cv2.cvtColor(ycrcb, cv2.COLOR_YCrCb2BGR)


def apply_channel_gains(bgr: np.ndarray, params: dict) -> np.ndarray:
    b_gain = clamp_float(params.get("b", 1.0), 0.0, 4.0)
    g_gain = clamp_float(params.get("g", 1.0), 0.0, 4.0)
    r_gain = clamp_float(params.get("r", 1.0), 0.0, 4.0)

    f = bgr.astype(np.float32)
    f[:, :, 0] *= b_gain
    f[:, :, 1] *= g_gain
    f[:, :, 2] *= r_gain

    return np.clip(f, 0, 255).astype(np.uint8)


def validate_gains(p: dict) -> dict:
    return {
        "b": clamp_float(p.get("b", 1.0), 0.0, 4.0),
        "g": clamp_float(p.get("g", 1.0), 0.0, 4.0),
        "r": clamp_float(p.get("r", 1.0), 0.0, 4.0),
    }


COLOR_SPECS: list[dict] = [
    {
        "id": "to_grayscale",
        "label": "Grayscale",
        "category": "color",
        "description": "Convert to grayscale and back to 3-channel for display.",
        "default_params": {},
        "apply": apply_to_grayscale,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "color_hsv_roundtrip",
        "label": "HSV round-trip",
        "category": "color",
        "description": "BGR → HSV → BGR.",
        "default_params": {},
        "apply": apply_bgr_to_hsv_and_back,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "color_lab_roundtrip",
        "label": "LAB round-trip",
        "category": "color",
        "description": "BGR → LAB → BGR.",
        "default_params": {},
        "apply": apply_bgr_to_lab_and_back,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "color_ycrcb_roundtrip",
        "label": "YCrCb round-trip",
        "category": "color",
        "description": "BGR → YCrCb → BGR.",
        "default_params": {},
        "apply": apply_bgr_to_ycrcb_and_back,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "channel_gains",
        "label": "Channel gains (BGR)",
        "category": "color",
        "description": "Multiply B, G, R channels.",
        "default_params": {"b": 1.0, "g": 1.0, "r": 1.0},
        "apply": apply_channel_gains,
        "validate_params": validate_gains,
    },
]

# CHANNEL + IMAGE ADJUSTMENTS
def apply_extract_channel(bgr: np.ndarray, params: dict) -> np.ndarray:
    channel_idx = clamp_int(params.get("channel", 0), 0, 2)
    single = bgr[:, :, channel_idx]
    return cv2.cvtColor(single, cv2.COLOR_GRAY2BGR)


def apply_bright_contrast(bgr: np.ndarray, params: dict) -> np.ndarray:
    alpha = clamp_float(params.get("contrast", 1.0), 0.0, 3.0)
    beta = clamp_int(params.get("brightness", 0), -100, 100)
    return cv2.convertScaleAbs(bgr, alpha=alpha, beta=beta)


def apply_color_threshold(bgr: np.ndarray, params: dict) -> np.ndarray:
    lower = np.array([
        clamp_int(params.get("min_blue", 0), 0, 255),
        clamp_int(params.get("min_green", 0), 0, 255),
        clamp_int(params.get("min_red", 0), 0, 255),
    ])

    upper = np.array([
        clamp_int(params.get("max_blue", 255), 0, 255),
        clamp_int(params.get("max_green", 255), 0, 255),
        clamp_int(params.get("max_red", 255), 0, 255),
    ])

    mask = cv2.inRange(bgr, lower, upper)
    return cv2.bitwise_and(bgr, bgr, mask=mask)


def validate_color(p: dict) -> dict:
    return {
        "channel": clamp_int(p.get("channel", 0), 0, 2),
        "contrast": clamp_float(p.get("contrast", 1.0), 0.0, 3.0),
        "brightness": clamp_int(p.get("brightness", 0), -100, 100),
        "min_blue": clamp_int(p.get("min_blue", 0), 0, 255),
        "max_blue": clamp_int(p.get("max_blue", 255), 0, 255),
        "min_green": clamp_int(p.get("min_green", 0), 0, 255),
        "max_green": clamp_int(p.get("max_green", 255), 0, 255),
        "min_red": clamp_int(p.get("min_red", 0), 0, 255),
        "max_red": clamp_int(p.get("max_red", 255), 0, 255),
    }


COLOR_ADDITIONS_SPECS: list[dict] = [
    {
        "id": "extract_channel",
        "label": "Extract Channel",
        "category": "color",
        "description": "Show a single B, G, or R channel.",
        "default_params": {"channel": 0},
        "apply": apply_extract_channel,
        "validate_params": validate_color,
    },
    {
        "id": "brightness_contrast",
        "label": "Brightness & Contrast",
        "category": "color",
        "description": "Adjust image brightness and contrast.",
        "default_params": {"contrast": 1.2, "brightness": 10},
        "apply": apply_bright_contrast,
        "validate_params": validate_color,
    },
    {
        "id": "color_threshold",
        "label": "Color Threshold",
        "category": "color",
        "description": "Keep pixels within a BGR range.",
        "default_params": {
            "min_blue": 0, "max_blue": 100,
            "min_green": 0, "max_green": 100,
            "min_red": 150, "max_red": 255
        },
        "apply": apply_color_threshold,
        "validate_params": validate_color,
    },
]
