# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EeYC7GK_3vfbgTH_ZO8ee9xUpZ5jKCru
"""

""" Geometric Operations — Flipping, Translation, and Affine Shearing. """

from __future__ import annotations

import cv2
import numpy as np

from app.cv_ops._params import clamp_float, clamp_int


#FLIP
def apply_flip(bgr: np.ndarray, params: dict) -> np.ndarray:
    # flip_code: 0 = vertical, 1 = horizontal, -1 = both
    mode = params.get("mode", "horizontal").lower()

    code = 1
    if mode == "vertical":
        code = 0
    elif mode == "both":
        code = -1

    return cv2.flip(bgr, code)


# TRANSLATE(SHIFT)
def apply_translate(bgr: np.ndarray, params: dict) -> np.ndarray:
    h, w = bgr.shape[:2]
    # Shift values can be negative
    tx = clamp_int(params.get("tx", 0), -w, w)
    ty = clamp_int(params.get("ty", 0), -h, h)

    # Translation matrix
    M = np.float32([[1, 0, tx], [0, 1, ty]])
    return cv2.warpAffine(bgr, M, (w, h))


# AFFINE SHEAR
def apply_shear(bgr: np.ndarray, params: dict) -> np.ndarray:
    h, w = bgr.shape[:2]
    shear_x = clamp_float(params.get("shear_x", 0.0), -1.0, 1.0)
    shear_y = clamp_float(params.get("shear_y", 0.0), -1.0, 1.0)

    # Shear matrix
    M = np.float32([[1, shear_x, 0], [shear_y, 1, 0]])
    return cv2.warpAffine(bgr, M, (w, h))


# VALIDATION
def validate_geometric(p: dict) -> dict:
    return {
        "mode": str(p.get("mode", "horizontal")),
        "tx": int(p.get("tx", 0)),
        "ty": int(p.get("ty", 0)),
        "shear_x": float(p.get("shear_x", 0.0)),
        "shear_y": float(p.get("shear_y", 0.0)),
    }


GEOMETRIC_ADDITIONS_SPECS: list[dict] = [
    {
        "id": "flip",
        "label": "Flip",
        "category": "geometric",
        "description": "Mirrors the image horizontally, vertically, or both.",
        "default_params": {"mode": "horizontal"},
        "apply": apply_flip,
        "validate_params": validate_geometric,
    },
    {
        "id": "translate",
        "label": "Translate (Shift)",
        "category": "geometric",
        "description": "Shifts the image along the X and Y axes.",
        "default_params": {"tx": 50, "ty": 0},
        "apply": apply_translate,
        "validate_params": validate_geometric,
    },
    {
        "id": "shear",
        "label": "Affine Shear",
        "category": "geometric",
        "description": "Tilts the image by shifting pixels proportionally to their coordinates.",
        "default_params": {"shear_x": 0.2, "shear_y": 0.0},
        "apply": apply_shear,
        "validate_params": validate_geometric,
    },
]