# -*- coding: utf-8 -*-
"""intensity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EeYC7GK_3vfbgTH_ZO8ee9xUpZ5jKCru
"""

# -*- coding: utf-8 -*-
""" Intensity + Histogram + Advanced Intensity Operations (Merged Module) """

from __future__ import annotations

import cv2
import numpy as np

from app.cv_ops._params import clamp_float, clamp_int, odd_kernel

# BASIC INTENSITY OPERATIONS

def apply_normalize_minmax(bgr: np.ndarray, params: dict) -> np.ndarray:
    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    out = cv2.normalize(gray, None, 0, 255, cv2.NORM_MINMAX)
    return cv2.cvtColor(out, cv2.COLOR_GRAY2BGR)


def apply_equalize_hist(bgr: np.ndarray, _params: dict) -> np.ndarray:
    ycrcb = cv2.cvtColor(bgr, cv2.COLOR_BGR2YCrCb)
    y, cr, cb = cv2.split(ycrcb)
    y2 = cv2.equalizeHist(y)
    merged = cv2.merge((y2, cr, cb))
    return cv2.cvtColor(merged, cv2.COLOR_YCrCb2BGR)


def apply_clahe(bgr: np.ndarray, params: dict) -> np.ndarray:
    clip = clamp_float(params.get("clip_limit", 2.0), 0.1, 40.0)
    gs = clamp_int(params.get("tile_grid_size", 8), 2, 32)

    lab = cv2.cvtColor(bgr, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)

    clahe = cv2.createCLAHE(clipLimit=clip, tileGridSize=(gs, gs))
    l2 = clahe.apply(l)

    merged = cv2.merge((l2, a, b))
    return cv2.cvtColor(merged, cv2.COLOR_LAB2BGR)


def apply_gamma(bgr: np.ndarray, params: dict) -> np.ndarray:
    g = clamp_float(params.get("gamma", 1.0), 0.1, 5.0)
    table = (np.linspace(0, 1, 256) ** g * 255).astype(np.uint8)
    return cv2.LUT(bgr, table)


def apply_invert(bgr: np.ndarray, _params: dict) -> np.ndarray:
    return cv2.bitwise_not(bgr)


_LOG256 = float(np.log(256.0))


def apply_log_transform(bgr: np.ndarray, _params: dict) -> np.ndarray:
    x = bgr.astype(np.float32)
    s = 255.0 * np.log1p(x) / _LOG256
    return np.clip(s, 0, 255).astype(np.uint8)


def apply_inverse_log_transform(bgr: np.ndarray, _params: dict) -> np.ndarray:
    s = bgr.astype(np.float32)
    r = np.exp(s / 255.0 * _LOG256) - 1.0
    return np.clip(r, 0, 255).astype(np.uint8)


# THRESHOLDING OPERATIONS
def apply_threshold_binary(bgr: np.ndarray, params: dict) -> np.ndarray:
    t = clamp_int(params.get("thresh", 127), 0, 255)
    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    _, bw = cv2.threshold(gray, t, 255, cv2.THRESH_BINARY)
    return cv2.cvtColor(bw, cv2.COLOR_GRAY2BGR)


def apply_threshold_otsu(bgr: np.ndarray, _params: dict) -> np.ndarray:
    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    _, bw = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    return cv2.cvtColor(bw, cv2.COLOR_GRAY2BGR)


def apply_threshold_adaptive_mean(bgr: np.ndarray, params: dict) -> np.ndarray:
    bs = odd_kernel(int(params.get("block_size", 11)), 3, 99)
    c = clamp_int(params.get("C", 2), -20, 20)

    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    bw = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C,
                               cv2.THRESH_BINARY, bs, c)
    return cv2.cvtColor(bw, cv2.COLOR_GRAY2BGR)


def apply_threshold_adaptive_gaussian(bgr: np.ndarray, params: dict) -> np.ndarray:
    bs = odd_kernel(int(params.get("block_size", 11)), 3, 99)
    c = clamp_int(params.get("C", 2), -20, 20)

    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    bw = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                               cv2.THRESH_BINARY, bs, c)
    return cv2.cvtColor(bw, cv2.COLOR_GRAY2BGR)

# ADVANCED INTENSITY EFFECTS
def apply_solarize(bgr: np.ndarray, params: dict) -> np.ndarray:
    t = clamp_int(params.get("threshold", 128), 0, 255)
    table = np.array([i if i < t else 255 - i for i in range(256)], dtype=np.uint8)
    return cv2.LUT(bgr, table)


def apply_posterize(bgr: np.ndarray, params: dict) -> np.ndarray:
    levels = clamp_int(params.get("levels", 4), 2, 64)
    step = 256 // levels
    return ((bgr // step) * step).astype(np.uint8)


def apply_threshold_ext(bgr: np.ndarray, params: dict) -> np.ndarray:
    t = clamp_int(params.get("threshold", 127), 0, 255)
    mode = str(params.get("mode", "truncate")).lower()

    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)

    if mode == "tozero":
        _, res = cv2.threshold(gray, t, 255, cv2.THRESH_TOZERO)
    else:
        _, res = cv2.threshold(gray, t, 255, cv2.THRESH_TRUNC)

    return cv2.cvtColor(res, cv2.COLOR_GRAY2BGR)

# VALIDATION
def validate_gamma(p: dict) -> dict:
    return {"gamma": clamp_float(p.get("gamma", 1.0), 0.1, 5.0)}


def validate_clahe(p: dict) -> dict:
    return {
        "clip_limit": clamp_float(p.get("clip_limit", 2.0), 0.1, 40.0),
        "tile_grid_size": clamp_int(p.get("tile_grid_size", 8), 2, 32),
    }


def validate_threshold_binary(p: dict) -> dict:
    return {"thresh": clamp_int(p.get("thresh", 127), 0, 255)}


def validate_adaptive(p: dict) -> dict:
    return {
        "block_size": odd_kernel(int(p.get("block_size", 11)), 3, 99),
        "C": clamp_int(p.get("C", 2), -20, 20),
    }


def validate_intensity_ext(p: dict) -> dict:
    return {
        "threshold": clamp_int(p.get("threshold", 127), 0, 255),
        "levels": clamp_int(p.get("levels", 4), 2, 64),
        "mode": str(p.get("mode", "truncate")),
    }

# REGISTRY (SPECS)
INTENSITY_SPECS: list[dict] = [
    {
        "id": "normalize_minmax",
        "label": "Normalize (Min-Max)",
        "category": "intensity",
        "description": "Stretch luminance to full 0–255 range.",
        "default_params": {},
        "apply": apply_normalize_minmax,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "equalize_histogram",
        "label": "Histogram Equalization",
        "category": "intensity",
        "description": "Enhances contrast using Y channel equalization.",
        "default_params": {},
        "apply": apply_equalize_hist,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "clahe",
        "label": "CLAHE",
        "category": "intensity",
        "description": "Adaptive histogram equalization in LAB space.",
        "default_params": {"clip_limit": 2.0, "tile_grid_size": 8},
        "apply": apply_clahe,
        "validate_params": validate_clahe,
    },
    {
        "id": "gamma",
        "label": "Gamma Correction",
        "category": "intensity",
        "description": "Adjust brightness using power-law transform.",
        "default_params": {"gamma": 1.0},
        "apply": apply_gamma,
        "validate_params": validate_gamma,
    },
    {
        "id": "invert",
        "label": "Invert",
        "category": "intensity",
        "description": "Flip intensities (negative image).",
        "default_params": {},
        "apply": apply_invert,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "log_transform",
        "label": "Log Transform",
        "category": "intensity",
        "description": "Compress dynamic range (enhances dark regions).",
        "default_params": {},
        "apply": apply_log_transform,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "inverse_log_transform",
        "label": "Inverse Log Transform",
        "category": "intensity",
        "description": "Restores image from log transform.",
        "default_params": {},
        "apply": apply_inverse_log_transform,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "threshold_binary",
        "label": "Binary Threshold",
        "category": "intensity",
        "description": "Simple global thresholding.",
        "default_params": {"thresh": 127},
        "apply": apply_threshold_binary,
        "validate_params": validate_threshold_binary,
    },
    {
        "id": "threshold_otsu",
        "label": "Otsu Threshold",
        "category": "intensity",
        "description": "Automatic threshold selection.",
        "default_params": {},
        "apply": apply_threshold_otsu,
        "validate_params": lambda p: dict(p),
    },
    {
        "id": "adaptive_mean",
        "label": "Adaptive Mean Threshold",
        "category": "intensity",
        "description": "Local mean-based thresholding.",
        "default_params": {"block_size": 11, "C": 2},
        "apply": apply_threshold_adaptive_mean,
        "validate_params": validate_adaptive,
    },
    {
        "id": "adaptive_gaussian",
        "label": "Adaptive Gaussian Threshold",
        "category": "intensity",
        "description": "Gaussian-weighted adaptive thresholding.",
        "default_params": {"block_size": 11, "C": 2},
        "apply": apply_threshold_adaptive_gaussian,
        "validate_params": validate_adaptive,
    },
    {
        "id": "solarize",
        "label": "Solarize",
        "category": "intensity",
        "description": "Inverts pixels above a threshold.",
        "default_params": {"threshold": 128},
        "apply": apply_solarize,
        "validate_params": validate_intensity_ext,
    },
    {
        "id": "posterize",
        "label": "Posterize",
        "category": "intensity",
        "description": "Reduces number of intensity levels.",
        "default_params": {"levels": 4},
        "apply": apply_posterize,
        "validate_params": validate_intensity_ext,
    },
    {
        "id": "threshold_ext",
        "label": "Threshold (Truncate/Tozero)",
        "category": "intensity",
        "description": "Advanced threshold modes.",
        "default_params": {"threshold": 127, "mode": "truncate"},
        "apply": apply_threshold_ext,
        "validate_params": validate_intensity_ext,
    },
]