# -*- coding: utf-8 -*-
"""segmentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROfaGP-FC-4xRQEVFUfzpCdiEVvrd231
"""

""" Segmentation Operations — Combined Basic and Advanced Methods.
Includes: K-Means, Watershed, GrabCut, SLIC Superpixels, and Connected Components. """

from __future__ import annotations

import cv2
import numpy as np

from app.cv_ops._params import clamp_int


# K-MEANS CLUSTERING (Color Quantization)
def apply_kmeans(bgr: np.ndarray, params: dict) -> np.ndarray:
    """Reduces the image to K dominant colors."""
    k = clamp_int(params.get("k", 4), 2, 32)
    attempts = 10
    data = bgr.reshape((-1, 3)).astype(np.float32)

    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)
    _, label, center = cv2.kmeans(data, k, None, criteria, attempts, cv2.KMEANS_RANDOM_CENTERS)

    center = np.uint8(center)
    res = center[label.flatten()]
    return res.reshape((bgr.shape))


# WATERSHED ALGORITHM (Automated)
def apply_watershed(bgr: np.ndarray, params: dict) -> np.ndarray:
    """Separates touching objects using topographic flooding."""
    thresh_val = clamp_int(params.get("threshold", 127), 1, 254)
    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)

    _, thresh = cv2.threshold(gray, thresh_val, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    kernel = np.ones((3,3), np.uint8)
    opening = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel, iterations=2)

    dist_transform = cv2.distanceTransform(opening, cv2.DIST_L2, 5)
    _, sure_fg = cv2.threshold(dist_transform, 0.7 * dist_transform.max(), 255, 0)

    sure_fg = np.uint8(sure_fg)
    unknown = cv2.subtract(opening, sure_fg)

    _, markers = cv2.connectedComponents(sure_fg)
    markers = markers + 1
    markers[unknown == 255] = 0

    markers = cv2.watershed(bgr, markers)

    unique_markers = np.unique(markers)
    colors = np.random.randint(0, 255, (len(unique_markers), 3), dtype=np.uint8)

    seg_img = np.zeros_like(bgr)
    for i, m_val in enumerate(unique_markers):
        if m_val <= 1: continue
        seg_img[markers == m_val] = colors[i]

    return cv2.addWeighted(bgr, 0.5, seg_img, 0.5, 0)


# GRABCUT (Foreground Extraction)
def apply_grabcut(bgr: np.ndarray, params: dict) -> np.ndarray:
    """Extracts foreground object based on a center-focused rectangle."""
    iter_count = clamp_int(params.get("iterations", 5), 1, 10)
    margin = clamp_int(params.get("margin_percent", 10), 1, 40)

    h, w = bgr.shape[:2]
    mx, my = int(w * margin / 100), int(h * margin / 100)
    rect = (mx, my, w - 2*mx, h - 2*my)

    mask = np.zeros(bgr.shape[:2], np.uint8)
    bgd_model = np.zeros((1, 65), np.float64)
    fgd_model = np.zeros((1, 65), np.float64)

    cv2.grabCut(bgr, mask, rect, bgd_model, fgd_model, iter_count, cv2.GC_INIT_WITH_RECT)
    mask2 = np.where((mask == 2) | (mask == 0), 0, 1).astype('uint8')

    return bgr * mask2[:, :, np.newaxis]


# SLIC SUPERPIXELS
def apply_superpixels(bgr: np.ndarray, params: dict) -> np.ndarray:
    """Groups pixels into clusters based on color and proximity."""
    num_segments = clamp_int(params.get("segments", 100), 10, 1000)

    if not hasattr(cv2, 'ximgproc'):
        # Fallback if opencv-contrib is not installed
        return bgr

    region_size = int(np.sqrt((bgr.shape[0]*bgr.shape[1])/num_segments))
    slic = cv2.ximgproc.createSuperpixelSLIC(bgr, algorithm=cv2.ximgproc.SLIC, region_size=region_size)
    slic.iterate(10)

    labels = slic.getLabels()
    mask = slic.getLabelContourMask()

    res = bgr.copy()
    for label in np.unique(labels):
        res[labels == label] = np.mean(bgr[labels == label], axis=0)

    res[mask == 255] = [0, 0, 0]
    return res


# CONNECTED COMPONENTS (Blob Labeling)
def apply_connected_components(bgr: np.ndarray, params: dict) -> np.ndarray:
    """Labels and colors distinct islands of pixels in a binary image."""
    thresh_val = clamp_int(params.get("threshold", 127), 1, 254)
    gray = cv2.cvtColor(bgr, cv2.COLOR_BGR2GRAY)
    _, binary = cv2.threshold(gray, thresh_val, 255, cv2.THRESH_BINARY)

    num_labels, labels = cv2.connectedComponents(binary)
    colors = np.random.randint(0, 255, (num_labels, 3), dtype=np.uint8)
    colors[0] = [0, 0, 0]

    return colors[labels]


# UNIFIED VALIDATION
def validate_segmentation(p: dict) -> dict:
    return {
        "k": clamp_int(p.get("k", 4), 2, 32),
        "threshold": clamp_int(p.get("threshold", 127), 1, 254),
        "iterations": clamp_int(p.get("iterations", 5), 1, 10),
        "margin_percent": clamp_int(p.get("margin_percent", 10), 1, 40),
        "segments": clamp_int(p.get("segments", 100), 10, 1000),
    }


# CONSOLIDATED SPECS
SEGMENTATION_SPECS: list[dict] = [
    {
        "id": "kmeans",
        "label": "K-Means Quantization",
        "category": "segmentation",
        "description": "Simplifies image into K dominant colors.",
        "default_params": {"k": 4},
        "apply": apply_kmeans,
        "validate_params": validate_segmentation,
    },
    {
        "id": "watershed",
        "label": "Watershed Segmentation",
        "category": "segmentation",
        "description": "Separates touching objects using topographic flooding.",
        "default_params": {"threshold": 127},
        "apply": apply_watershed,
        "validate_params": validate_segmentation,
    },
    {
        "id": "grabcut",
        "label": "GrabCut (FG Extraction)",
        "category": "segmentation",
        "description": "Smart background removal for central objects.",
        "default_params": {"iterations": 5, "margin_percent": 10},
        "apply": apply_grabcut,
        "validate_params": validate_segmentation,
    },
    {
        "id": "superpixels",
        "label": "SLIC Superpixels",
        "category": "segmentation",
        "description": "Partitions image into clusters based on color/proximity.",
        "default_params": {"segments": 200},
        "apply": apply_superpixels,
        "validate_params": validate_segmentation,
    },
    {
        "id": "connected_blobs",
        "label": "Connected Components",
        "category": "segmentation",
        "description": "Labels separate islands of pixels. Useful for counting.",
        "default_params": {"threshold": 127},
        "apply": apply_connected_components,
        "validate_params": validate_segmentation,
    },
]