# Writes frontend/.env and backend/.env from kernellab.env in the repo root.
# Usage (from repo root): .\scripts\sync-kernellab-env.ps1

$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..")
$src = Join-Path $root "kernellab.env"

if (-not (Test-Path $src)) {
    Write-Error "Missing $src - copy kernellab.env.example to kernellab.env and fill in."
}

$fe = [System.Collections.Generic.List[string]]::new()
$be = [System.Collections.Generic.List[string]]::new()
$fe.Add("# Generated by scripts/sync-kernellab-env.ps1 (do not commit)")
$be.Add("# Generated by scripts/sync-kernellab-env.ps1 (do not commit)")

Get-Content -LiteralPath $src -Encoding utf8 | ForEach-Object {
    $line = $_
    $trim = $line.Trim()
    if ($trim -eq "" -or $trim.StartsWith("#")) {
        return
    }
    $eq = $trim.IndexOf("=")
    if ($eq -lt 1) { return }
    $key = $trim.Substring(0, $eq).Trim()
    if ($key.StartsWith("VITE_")) {
        $fe.Add($trim)
    }
    else {
        $be.Add($trim)
    }
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines((Join-Path $root "frontend\.env"), $fe, $utf8NoBom)
[System.IO.File]::WriteAllLines((Join-Path $root "backend\.env"), $be, $utf8NoBom)

Write-Host "Wrote frontend/.env and backend/.env"
